### ISSUE TITLE
Pack issue [SOLVED]

### ISSUE THREAD

**Issue by BrizzleMFD** [CustomCheat/LinuxCurse#1]
Pack Name: Create: Above and Beyond
locates pack just fine by typing yes fails to download pack
![image](https://user-images.githubusercontent.com/8378250/145732052-f1f017d9-749e-4c54-a823-4f3d7dc210e6.png)

**Comment by MikeyMayukhYT** [comment]
same happend to me no fix yet

**Comment by MikeyMayukhYT** [comment]
Nevermind i found a solution just follow these steps

first put half of the name of the modpack
![image](https://user-images.githubusercontent.com/77010784/148017103-e96894e0-372d-4718-b35e-cffca8594941.png)


second put your modpack name with the caps
![image](https://user-images.githubusercontent.com/77010784/148017171-8ddcd70b-936f-486d-9761-bba76791b09f.png)


then it should start downloading

**Comment by CustomCheat** [comment]
I did just realise that was actually a problem it was because the create and beyond has a colon in the name. Did close this too early. But it is fixed after the month! Well at least its fixed.
