### ISSUE TITLE
Modpack not running (Create: Above and Beyond) [Fixed]

### ISSUE THREAD

**Issue by Anshuman1210** [CustomCheat/LinuxCurse#3]
the create above and beyond is not running

**Comment by CustomCheat** [comment]
I did recreate this will try my best to find the bug

**Comment by CustomCheat** [comment]
Fixed please test it now and confirm that it is fixed if u don't reply within the next 24 hours this issues will be marked as solved

**Comment by Anshuman1210** [comment]
hey what keyword of the mod pack should i input fore create above and beyond
