### ISSUE TITLE
Cannot launch Create: Above and Beyond [FIXED]

### ISSUE THREAD

**Issue by Anshuman1210** [CustomCheat/LinuxCurse#5]
I can't launch create: above and beyond

**Comment by Anshuman1210** [comment]
Its installed but cant launch

**Comment by CustomCheat** [comment]
Did u reinstall the modpack with the new version? You should use just create keyword and it will find it I think I will look into this when I'm on a computer I launched it without problems 5 days ago

**Comment by Anshuman1210** [comment]
how do i reinstall?

**Comment by CustomCheat** [comment]
Just download the project again and install the modpack again, i fixed a bug in the new version that i released like 10 days ago. If u do already have the newest version, what is your distro and your java,python version? That can be caused by many things

**Comment by CustomCheat** [comment]
I can launch the modpack and it works without issues my output: https://pastebin.com/ue2gimyw
image from the main menu: https://ibb.co/5jccyfj
Image from the game: https://ibb.co/YQ6gCWJ
Try to reinstall it and reply if u still have problems, if u don't have any problems with it, please reply that it works

**Comment by Anshuman1210** [comment]
> Just download the project again and install the modpack again, i fixed a bug in the new version that i released like 10 days ago. If u do already have the newest version, what is your distro and your java,python version? That can be caused by many things

Python = 3.8.10

**Comment by Anshuman1210** [comment]
Ok ima reinstall

**Comment by Anshuman1210** [comment]
it launches the officil launcher, but i cant see the installation of the mdpack anywhere

**Comment by Anshuman1210** [comment]
Yea now its working

**Comment by Anshuman1210** [comment]
but kinda laggy

**Comment by CustomCheat** [comment]
Well u can install mods such as OptiForge. Just copy the Optiforge mod to the modpack folder go into the LinuxCurse folder then go into the folder that is the modpack name then .minecraft (this can be not shown use the terminal or Google how to show files with the . ) Then copy the optifine jar from the official optifine page to the mods and done. And turn down the settings. This is probably just the limit of hardware not software. Maybe the modpack is not optimised. Keep in mind that these modpacks have been designed for Windows.

**Comment by Anshuman1210** [comment]
close this issue now
